spring.application.name=tir-exchage-service

server.port=8085

spring.datasource.url=jdbc:postgresql://localhost:5432/tir_epd
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

springdoc.show-actuator=true

management.endpoints.web.exposure.include=health,info,metrics,env,loggers,threaddump,httptrace
management.endpoint.health.show-details=always
management.health.db.enabled=true
management.health.diskspace.enabled=true
#port for actuator
#management.server.port=8086

spring.jpa.hibernate.ddl-auto=update

spring.jackson.serialization.indent-output=true

logging.file.name=logs/tir-exchange.log
